version: '3.8'

services:
  app:
    image: rust:latest
    container_name: cli_rust_tool
    restart: always
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8003:8003"
